### ISSUE TITLE
M15 Mainframe Style: Pure Enchantments use wrong base frame

### ISSUE THREAD

**Issue by DivineGodlyBovine** [MagicSetEditorPacks/M15-Magic-Pack#11]
Recently I got a fresh copy of MSE (within the past two weeks of creating this issue), so I'm not sure when this began in general, but for me, pure Enchantments seem to have an issue (pure Enchantment meaning a card that is only an enchantment and no other card type).

What was expected:
M15 Mainframe style Pure Enchantment cards should use the default frame for their color(s).

What happened:
Pure enchantments use the Nyx enchantment border automatically, with no way to disable.

Current workaround: 
Using M15 Style.  This is less effective since that style is missing settings, but usable.

Steps taken for troubleshooting:
Changing all options in the Style tab for a given card. None change the frame.

This could be me being a Stupid Idiot but I figure if so, it would give other people a chance to see that they were also being one and what they may have also missed.
(Also hey, it's Gurf 👋 )

**Comment by CajunAvenger** [comment]
normal enchantments will be using the Nyx frame starting in Foundations (the set that comes out in a month or two). It can be disabled with the "Auto nyx" option in the Set tab if you want.
(hey gurf)

**Comment by DivineGodlyBovine** [comment]
Oh, interesting.  I believe you, but is there somewhere where Foundations stuff is shown to do that? Mainly out of curiosity.  

Not sure I personally like that but WotC knows best and can do no wrong, as we all know.

**Comment by CajunAvenger** [comment]
https://scryfall.com/search?q=set%3Afdn+t%3Aenchantment&unique=cards&as=grid&order=set
