### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Reyn-Fox** [MagicSetEditorPacks/M15-Magic-Pack#4]
Can any programmer recompile MSE with a dark mode function? 
Simply to change the backgrounds from white to black (or dark grey) would be ideal.
I think many users would greatly appreciate this, [as per this thread](https://magicseteditor.boards.net/thread/1938/dark-mode?page=1).

**Comment by CajunAvenger** [comment]
not something we have the ability to add unfort
