### ISSUE TITLE
Trojan 

### ISSUE THREAD

**Issue by User901981** [MagicSetEditorPacks/M15-Magic-Pack#9]
I’ve just downloaded this program off of this page. After extracting the files I’ve received **several Trojan warnings in the MSE files** from windows defender. 

What the flip!?

**Comment by CajunAvenger** [comment]
does it give you a list of particular files?

some amount of this is your computer not liking you downloaded an exe. i think there might be some amount that it doesn't like the new image compression we used.

**Comment by User901981** [comment]
Yeah I’ve checked other sites and I genuinely don’t think that a program so frequently used is infested with viruses.

In the moment I just thought I’d reach out. Apparently it has something to do with windows defender machine learning algorithms and .exe files. 

So far everything is operating normally so probably just a false alarm.
